### ISSUE TITLE
Unused scipy.stats imported as ss

### ISSUE THREAD

**Issue by sajeetharan** [DuoSoftware/DigInEngine#1]
#### Occurred on:
+ **Commit**:  638a41159827f313782bf2759f1e7829de9fabf6
+ **File**:    [modules/HoltWinter.py](https://github.com/DuoSoftware/DigInEngine/blob/638a41159827f313782bf2759f1e7829de9fabf6/modules/HoltWinter.py)
+ **LineNum**: [3](https://github.com/DuoSoftware/DigInEngine/blob/638a41159827f313782bf2759f1e7829de9fabf6/modules/HoltWinter.py#L3)
+ **Code**:    `import scipy.stats as ss`

    
#### Currently on:
+ **Commit**:  48b23b3c0e5d389cd77fce68e95f0dcb929453c2
+ **File**:    [modules/HoltWinter.py](https://github.com/DuoSoftware/DigInEngine/blob/48b23b3c0e5d389cd77fce68e95f0dcb929453c2/modules/HoltWinter.py)
+ **LineNum**: [3](https://github.com/DuoSoftware/DigInEngine/blob/48b23b3c0e5d389cd77fce68e95f0dcb929453c2/modules/HoltWinter.py#L3)

**Comment by MarlonAbeykoon** [comment]
Removed unused import
